-- for testing only
GRANT ALL ON SCHEMA public TO batonpass;
GRANT ALL PRIVILEGES ON DATABASE batonpass TO batonpass;
GRANT ALL PRIVILEGES ON DATABASE test TO batonpass;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO batonpass;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO batonpass;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO batonpass;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO batonpass;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO batonpass;
